apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend-deploy
spec:
  replicas: {{ .Values.app.frontendreplicaCount}}
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: {{ .Values.images.frontend}} 
        imagePullPolicy: Always
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: /api
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-file