FROM python:3.9-slim

WORKDIR /app

COPY /kafka-restaurants/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#COPY . .
COPY /kafka-restaurants/backend/search_order.py /app
COPY /kafka-restaurants/backend/restaurants.json /app

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the Flask app
CMD ["python", "search_order.py"]

# From the root dir
# docker build -t searchorder:0.0.1 -f .\docker\dockerfile-flask   