FROM python:3.9-slim

WORKDIR /app

COPY /kafka-restaurants/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /kafka-restaurants/backend/py-email.py /app

RUN chmod +x py-email.py

# Set the entrypoint to the CLI script
ENTRYPOINT ["python", "py-email.py"]

# From the root dir
# docker build -t pyemail:0.0.1 -f .\docker\dockerfile-pymail .  