FROM nginx:latest

COPY docker/entrypointfrontend.sh .
COPY /kafka-restaurants/frontend/ /usr/share/nginx/html

EXPOSE 8088

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Start Nginx server
CMD ["/entrypoint.sh"]

# From the root dir
# docker build -t frontend:0.0.1 -f .\docker\dockerfile-frontend .  

#docker run --name frontend-container --network app-network \
#-e API_URL=https://production.example.com \
#-p 8088:80 \
#-d ferestaurants:0.0.1

