FROM python:3.9-slim

WORKDIR /app

COPY /kafka-restaurants/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#COPY . .
COPY /kafka-restaurants/backend/search_order.py /app
# You dont need the config file if you deploy it with the helm chart. it will be in the configMap
# and will be mount as volume to app/config
COPY /kafka-restaurants/backend/config/restaurants.json /app/config/

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the Flask app
CMD ["python", "search_order.py"]

# From the root dir
# docker build -t searchorder:0.0.1 -f .\docker\dockerfile-flask   